### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by colachg** [helm/chartmuseum#206]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe1a9ef]

goroutine 1 [running]:
github.com/helm/chartmuseum/pkg/chartmuseum/router.NewRouter(0xc000132720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/helm/chartmuseum/pkg/chartmuseum/router/router.go:135 +0x6df
github.com/helm/chartmuseum/pkg/chartmuseum.NewServer(0x13c5c20, 0xc00053e1d0, 0x0, 0x0, 0xc0000360aa, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server.go:83 +0x28a
main.cliHandler(0xc000129080)
	/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:96 +0xa05
github.com/helm/chartmuseum/vendor/github.com/urfave/cli.HandleAction(0xfd22a0, 0x1253250, 0xc000129080, 0xc00012b8c0, 0x0)
	/go/src/github.com/helm/chartmuseum/vendor/github.com/urfave/cli/app.go:492 +0x7c
github.com/helm/chartmuseum/vendor/github.com/urfave/cli.(*App).Run(0xc0001a5ba0, 0xc00002e090, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/helm/chartmuseum/vendor/github.com/urfave/cli/app.go:264 +0x59d
main.main()
	/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:52 +0x1bd
```

I install it with helm chart.
```
      chart: "stable/chartmuseum"
      version: "1.8.4"
```
This is my error log. I found that if I set `env.open.AUTH_ANONYMOUS_GET: true`, the pod will be CrashLoopBackOff.

**Comment by colachg** [comment]
@jdolitsky Could you help me?

**Comment by jdolitsky** [comment]
@colachg appreciate your patience, I will try to reproduce this shortly

If you `helm delete --purge` and try again, does this go away?

**Comment by jdolitsky** [comment]
@colachg of course. in `v0.8.1` it is needed, in `latest` (master) it is optional

**Comment by rajatvig** [comment]
When is `v0.9.0` planned to be released?

**Comment by jdolitsky** [comment]
@rajatvig are you running into this issue as well? Was hoping to get a new storage option added prior to release (etcd) but not sure how soon this will be

**Comment by rajatvig** [comment]
@jdolitsky yes. Have opted to use latest to get it going for now. If the release is more than a week off, could you please do a `v0.8.2` release in the interim?
Using the `latest` tag does not seem stable.

**Comment by jdolitsky** [comment]
@rajatvig fair enough! will look into a 0.8.2 today

**Comment by jdolitsky** [comment]
@rajatvig @colachg v0.8.2 is now released with a fix for this! Thank you for your patience
```
$ docker run --rm chartmuseum/chartmuseum:v0.8.2 --version
ChartMuseum version 0.8.2 (build 91d9b5d)
```
