### ISSUE TITLE
CAN NOT access ceph object storage via swift

### ISSUE THREAD

**Issue by jeremyxu2010** [helm/chartmuseum#211]
I setup a ceph object storage and enable swift access. try to access ceph via swift, successed:

```bash
# swift -A http://10.125.224.26:7480/auth/v1.0 -U tstack:swift -K tstackqwer666 list
regswfit
test
```

then, i want use chartmuseum to access ceph object storage via swift:

```bash
export OS_AUTH_URL=http://10.125.224.26:7480/auth/v1.0
export OS_USERNAME=tstack:swift
export OS_PASSWORD=tstackqwer666
export STORAGE: openstack
export STORAGE_OPENSTACK_CONTAINER=regswfit
export STORAGE_OPENSTACK_REGION=openstack

./chartmuseum
```

then error happened:

```
panic: Openstack (authenticate): Authentication failed

goroutine 1 [running]:
github.com/helm/chartmuseum/vendor/github.com/kubernetes-helm/chartmuseum/pkg/storage.NewOpenstackOSBackend(0xc00003613c, 0x8, 0x0, 0x0, 0xc0000360a9, 0x9, 0x0, 0x0, 0x0)
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/vendor/github.com/kubernetes-helm/chartmuseum/pkg/storage/openstack.go:94 +0xcc7
main.openstackBackendFromConfig(0xc0002202c0, 0x0, 0x0)
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:158 +0x218
main.backendFromConfig(0xc0002202c0, 0x0, 0x0)
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:100 +0x9a2
main.cliHandler(0xc000272dc0)
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:46 +0x15e
github.com/helm/chartmuseum/vendor/github.com/urfave/cli.HandleAction(0x12597e0, 0x14a5868, 0xc000272dc0, 0x0, 0x0)
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/vendor/github.com/urfave/cli/app.go:492 +0x1cc
github.com/helm/chartmuseum/vendor/github.com/urfave/cli.(*App).Run(0xc000319380, 0xc0000301b0, 0x1, 0x1, 0x0, 0x0)
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/vendor/github.com/urfave/cli/app.go:264 +0xa53
main.main()
	/home/xinjiexu/workspace/dev_projs/tcnp/gopath/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:36 +0x2a5
```

chartmuseum version: 0.7.1
ceph version: 12.2.4 (52085d5249a80c5f5121a76d6288429f35e4e77b) luminous (stable)

**Comment by jdolitsky** [comment]
@jeremyxu2010 hi there, sorry you're having issues. I don't have a lot of experience running chartmuseum with openstack storage.

You may wish to take a look at the code that handles this to see if there are any glaring issues:
https://github.com/chartmuseum/storage/blob/master/openstack.go

And this seems to be the piece in the 3rd-party lib that handles the Auth variables etc.:
https://github.com/gophercloud/gophercloud/blob/master/openstack/auth_env.go#L33

Pinging original author of openstack support @gmauleon - do you have any tips?

**Comment by jeremyxu2010** [comment]
I notice gophercloud's openstack library only supports v2/v3 authorize method. But I configure the swift access **with ceph only(without keystone)**, ceph **only support v1 authorize** method.

@jdolitsky @gmauleon 

`https://github.com/gophercloud/gophercloud/blob/master/openstack/client.go`

```go
// Authenticate or re-authenticate against the most recent identity service
// supported at the provided endpoint.
func Authenticate(client *gophercloud.ProviderClient, options gophercloud.AuthOptions) error {
	versions := []*utils.Version{
		{ID: v2, Priority: 20, Suffix: "/v2.0/"},
		{ID: v3, Priority: 30, Suffix: "/v3/"},
	}

	chosen, endpoint, err := utils.ChooseVersion(client, versions)
	if err != nil {
		return err
	}

	switch chosen.ID {
	case v2:
		return v2auth(client, endpoint, options, gophercloud.EndpointOpts{})
	case v3:
		return v3auth(client, endpoint, &options, gophercloud.EndpointOpts{})
	default:
		// The switch statement must be out of date from the versions list.
		return fmt.Errorf("Unrecognized identity version: %s", chosen.ID)
	}
}
```

**Comment by jdolitsky** [comment]
@jeremyxu2010 Is it possible to configure your service with v2/v3 support and try again?

**Comment by gmauleon** [comment]
I guess that would make the most sense to try and change it on the Ceph side if possible (short of changing the openstack client in chartmuseum, but gophercloud is the de facto standard actually, since it's the same used by Kubernetes)

**Comment by jeremyxu2010** [comment]
@jdolitsky ceph itself (without keystone) only support v1 authorize method，so Can chartmuseum support ceph's swift or s3?

**Comment by jdolitsky** [comment]
@jeremyxu2010 sorry for delay. You can use S3 as a storage backend, but I'm not sure if that answers your question

**Comment by jeremyxu2010** [comment]
@jdolitsky I tried ceph object storage via S3, it's OK! But docker's registry CAN NOT support ceph's object storage via S3. See [here](https://github.com/docker/distribution/issues/2189), in this post, someone said docker registry BE NOT compatible with ceph's S3, he suggested use ceph object storage via SWIFT.  
So I want docker registry and chartmuseum use the same storage backend  "ceph", what i should to choose?

**Comment by jdolitsky** [comment]
@jeremyxu2010 I see. So basically ChartMuseum does not have a backend option compatible with Swift API.

However, other people have successfully used ChartMuseum with Ceph. Maybe this helm chart config snippet will help? https://github.com/helm/charts/tree/master/stable/chartmuseum#example-storage-class

If you must use Swift, the support must first be added in [chartmuseum/storage](https://github.com/chartmuseum/storage)
