### ISSUE TITLE
An error is reported after upgrading the latest version of chartuseum

### ISSUE THREAD

**Issue by duanhongyi** [helm/chartmuseum#375]
The same configuration has no problem in v0.11.0. After upgrading to v0.12.0, the following errors occur:

```
2020-09-18T06:21:25.936850+00:00 heroku[web.1]: Process exited with status 2
2020-09-18T06:21:25.973220+00:00 heroku[web.1]: State changed from up to crashed
2020-09-18T06:21:25.975299+00:00 heroku[web.1]: State changed from crashed to starting
2020-09-18T06:21:27.183577+00:00 heroku[web.1]: Starting process with command `/chartmuseum --cache\=redis --cache-redis-addr\=ec2-54-246-108-210.eu-west-1.compute.amazonaws.com:28989 --cache-redis-password\=pdb78a309a401cf1132178f53c3ab60d0552870159c7a31217ff5bf8fe9a03eba --port\=\50601 --cache-interval\=1m --chart-url\=https://charts-drycc.oss-accelerate.aliyuncs.com`
2020-09-18T06:21:29.107167+00:00 app[web.1]: 2020-09-18T06:21:29.107Z	INFO	Starting ChartMuseum	{"port": 50601}
2020-09-18T06:21:29.474144+00:00 heroku[web.1]: State changed from starting to up
2020-09-18T06:21:31.759679+00:00 app[web.1]: panic: runtime error: invalid memory address or nil pointer dereference
2020-09-18T06:21:31.759730+00:00 app[web.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x10302de]
2020-09-18T06:21:31.759731+00:00 app[web.1]: 
2020-09-18T06:21:31.759732+00:00 app[web.1]: goroutine 125 [running]:
2020-09-18T06:21:31.759734+00:00 app[web.1]: helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc000b22800, 0x6b, 0x80, 0x6b, 0x80, 0x0)
2020-09-18T06:21:31.759734+00:00 app[web.1]: /codefresh/volume/gopath/pkg/mod/helm.sh/helm/v3@v3.1.2/pkg/chart/loader/load.go:126 +0xa7e
2020-09-18T06:21:31.759735+00:00 app[web.1]: helm.sh/helm/v3/pkg/chart/loader.LoadArchive(0x22ad980, 0xc0000a5ce0, 0xed54c28ea, 0x0, 0x0)
2020-09-18T06:21:31.759738+00:00 app[web.1]: /codefresh/volume/gopath/pkg/mod/helm.sh/helm/v3@v3.1.2/pkg/chart/loader/archive.go:193 +0x87
2020-09-18T06:21:31.759754+00:00 app[web.1]: helm.sh/chartmuseum/pkg/repo.chartFromContent(...)
2020-09-18T06:21:31.759758+00:00 app[web.1]: /codefresh/volume/chartmuseum/pkg/repo/chart.go:98
2020-09-18T06:21:31.759800+00:00 app[web.1]: helm.sh/chartmuseum/pkg/repo.ChartVersionFromStorageObject(0xc0005e7560, 0x1a, 0xc00084e000, 0x45af, 0x7e00, 0x0, 0xed54c28ea, 0x0, 0x0, 0xed54c28ea, ...)
2020-09-18T06:21:31.759804+00:00 app[web.1]: /codefresh/volume/chartmuseum/pkg/repo/chart.go:70 +0x14a
2020-09-18T06:21:31.759851+00:00 app[web.1]: helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getObjectChartVersion(0xc0001b3e00, 0xc0001b9e45, 0x6, 0xc0005e7560, 0x1a, 0xc00084e000, 0x45af, 0x7e00, 0x0, 0xed54c28ea, ...)
2020-09-18T06:21:31.759859+00:00 app[web.1]: /codefresh/volume/chartmuseum/pkg/chartmuseum/server/multitenant/cache.go:301 +0x83
2020-09-18T06:21:31.759917+00:00 app[web.1]: helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).addIndexObjectsAsync.func1(0xc0001b3e00, 0x22fbf60, 0xc00047ee40, 0xc0001b9e45, 0x6, 0xc000341600, 0xc000725090, 0xc000612180, 0xc0005e7500, 0x13, ...)
2020-09-18T06:21:31.759921+00:00 app[web.1]: /codefresh/volume/chartmuseum/pkg/chartmuseum/server/multitenant/cache.go:257 +0x139
2020-09-18T06:21:31.759926+00:00 app[web.1]: created by helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).addIndexObjectsAsync
2020-09-18T06:21:31.759968+00:00 app[web.1]: /codefresh/volume/chartmuseum/pkg/chartmuseum/server/multitenant/cache.go:245 +0x33f
2020-09-18T06:21:31.765058+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/stable/index.yaml" host=drycc-charts.herokuapp.com request_id=1b99cd28-4c54-4b03-8c75-fc40c542e722 fwd="175.164.27.166, 172.69.35.60,47.246.18.151" dyno=web.1 connect=0ms service=1369ms status=503 bytes=0 protocol=http
2020-09-18T06:21:31.820309+00:00 heroku[web.1]: Process exited with status 2
2020-09-18T06:21:31.846820+00:00 heroku[web.1]: State changed from up to crashed
2020-09-18T06:21:32.344610+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/stable/index.yaml" host=drycc-charts.herokuapp.com request_id=13631a99-a881-4593-b374-366f5e63e063 fwd="175.164.27.166, 172.69.35.60,47.246.18.150" dyno= connect= service= status=503 bytes= protocol=http
^C
```

**Comment by jdolitsky** [comment]
Hi, sorry youre having issues. Here is a few ideas:

- v0.12.0 does not contain the `--cache-interval` option, this is not yet released
- it appears you are not specifying `--storage` options.. are these set as environment variables?
- it looks like you are attempting to GET /stable/index.yaml, however you have not specified `--depth=1`

I think have more information about relevant environment variables will help debug this

**Comment by duanhongyi** [comment]
This is my problem. There is a package that does not meet the helm3 specification; this error occurs when chartuseum uses helm repo index.
