### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lvxiaohu** [helm/chartmuseum#401]
chartmuseum version: latest arm64
storage class: NFS
kubernetes version: v1.18.10

goroutine 1 [running]:

```
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFile(0x400078efc0, 0x4000790640, 0x0, 0x0, 0x4000412ac0, 0x4000412b00)

        /go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server/multitenant/index.go:43 +0x64

helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).primeCache(0x400078efc0, 0x4000530600, 0xd)

        /go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server/multitenant/cache.go:87 +0x74

helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.NewMultiTenantServer(0x400052e0f0, 0x400079c000, 0x1c07420, 0x40008abc10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x400004205b, ...)

        /go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server/multitenant/server.go:147 +0x268

helm.sh/chartmuseum/pkg/chartmuseum.NewServer(0x1c07420, 0x40008abc10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

        /go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server.go:123 +0x318

main.cliHandler(0x4000590000)

        /go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:107 +0x97c

github.com/urfave/cli.HandleAction(0x1545860, 0x19a97c0, 0x4000590000, 0x4000590000, 0x0)

        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:526 +0x5c

github.com/urfave/cli.(*App).Run(0x4000148000, 0x400018c000, 0x3, 0x3, 0x0, 0x0)

        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x458
```

main.main()

        /go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:51 +0x1d8

**Comment by scbizu** [comment]
Thanks for opening the issue , can you share your museum startup command ?
